apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.22-rootless
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 2222
              name: ssh
          volumeMounts:
            - name: gitea-data
              mountPath: /var/lib/gitea
      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-service
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
    - port: 2222
      targetPort: 2222
      name: ssh
  selector:
    app: gitea
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-ingress
spec:
  entryPoints: [web]
  routes:
  - match: Host(`berry`) && PathPrefix(`/gitea`)
    kind: Rule
    services:
    - name: gitea-service
      port: 3000
    middlewares:
    - name: gitea-stripprefix
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gitea-stripprefix
spec:
  stripPrefix:
    prefixes:
    - /gitea
